/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multiple_screen;

/**
 *
 * @author Jacobe
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        ButtonPanel1 = new javax.swing.JPanel();
        ButtonLbl1 = new javax.swing.JLabel();
        ButtonPanel2 = new javax.swing.JPanel();
        ButtonLbl2 = new javax.swing.JLabel();
        ButtonPanel3 = new javax.swing.JPanel();
        ButtonLbl3 = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        Screen1Panel = new javax.swing.JPanel();
        SubScreen1Panel = new javax.swing.JPanel();
        Screen2Panel = new javax.swing.JPanel();
        SubScreen2Panel = new javax.swing.JPanel();
        Screen3Panel = new javax.swing.JPanel();
        SubScreen3Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(29, 85, 77));
        SidePanel.setPreferredSize(new java.awt.Dimension(240, 720));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanel1.setBackground(new java.awt.Color(153, 102, 255));
        ButtonPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonLbl1.setBackground(new java.awt.Color(153, 102, 255));
        ButtonLbl1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ButtonLbl1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonLbl1.setText("Screen 1");
        ButtonLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLbl1MouseClicked(evt);
            }
        });
        ButtonPanel1.add(ButtonLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 240, 50));

        SidePanel.add(ButtonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 50));

        ButtonPanel2.setBackground(new java.awt.Color(0, 153, 255));
        ButtonPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonLbl2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ButtonLbl2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonLbl2.setText("Screen 2");
        ButtonLbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonLbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLbl2MouseClicked(evt);
            }
        });
        ButtonPanel2.add(ButtonLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 240, 50));

        SidePanel.add(ButtonPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 50));

        ButtonPanel3.setBackground(new java.awt.Color(102, 0, 0));
        ButtonPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonLbl3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ButtonLbl3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonLbl3.setText("Screen 3");
        ButtonLbl3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonLbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLbl3MouseClicked(evt);
            }
        });
        ButtonPanel3.add(ButtonLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -3, 240, 50));

        SidePanel.add(ButtonPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 50));

        MainPanel.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        Screen1Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubScreen1Panel.setBackground(new java.awt.Color(153, 102, 255));
        SubScreen1Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Screen1Panel.add(SubScreen1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        TabbedPane.addTab("Screen 1", Screen1Panel);

        Screen2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubScreen2Panel.setBackground(new java.awt.Color(0, 153, 255));
        SubScreen2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Screen2Panel.add(SubScreen2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        TabbedPane.addTab("Screen 2", Screen2Panel);

        Screen3Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubScreen3Panel.setBackground(new java.awt.Color(102, 0, 0));
        SubScreen3Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Screen3Panel.add(SubScreen3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        TabbedPane.addTab("Screen 3", Screen3Panel);

        MainPanel.add(TabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 720));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLbl1MouseClicked
        // Screen 1 Button
     
        TabbedPane.setSelectedIndex(0);

    }//GEN-LAST:event_ButtonLbl1MouseClicked

    private void ButtonLbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLbl2MouseClicked
        // Screen 2 Button
        
        TabbedPane.setSelectedIndex(1);
        
    }//GEN-LAST:event_ButtonLbl2MouseClicked

    private void ButtonLbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLbl3MouseClicked
        // Screen 3 Button
        
        TabbedPane.setSelectedIndex(2);
        
    }//GEN-LAST:event_ButtonLbl3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonLbl1;
    private javax.swing.JLabel ButtonLbl2;
    private javax.swing.JLabel ButtonLbl3;
    private javax.swing.JPanel ButtonPanel1;
    private javax.swing.JPanel ButtonPanel2;
    private javax.swing.JPanel ButtonPanel3;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Screen1Panel;
    private javax.swing.JPanel Screen2Panel;
    private javax.swing.JPanel Screen3Panel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel SubScreen1Panel;
    private javax.swing.JPanel SubScreen2Panel;
    private javax.swing.JPanel SubScreen3Panel;
    private javax.swing.JTabbedPane TabbedPane;
    // End of variables declaration//GEN-END:variables
}
